# Generated by Django 4.0.10 on 2023-05-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0002_remove_combohistory_date_remove_moves_base_move_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moves',
            name='base_move',
            field=models.CharField(blank=True, choices=[('CrossBody', 'CrossBody'), ('Hamalock', 'Hamalock'), ('Kopa', 'Kopa'), ('OpenBreak', 'OpenBreak')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moves',
            name='entry_hold',
            field=models.CharField(blank=True, choices=[('Left2Left', 'Left2Left'), ('Right2Right', 'Right2Right'), ('Right2Left', 'Right2Left'), ('Left2Right', 'Left2Right'), ('Both', 'Both')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moves',
            name='exit_hold',
            field=models.CharField(blank=True, choices=[('Left2Left', 'Left2Left'), ('Right2Right', 'Right2Right'), ('Right2Left', 'Right2Left'), ('Left2Right', 'Left2Right'), ('Both', 'Both')], max_length=20, null=True),
        ),
    ]
