# Generated by Django 4.0.10 on 2023-05-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0003_moves_base_move_moves_entry_hold_moves_exit_hold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moves',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='combos',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moves',
            name='difficulty_of_move',
            field=models.CharField(blank=True, choices=[(1, 'Can always do in socials'), (2, 'Can sometimes do in socials'), (3, 'Cant do in socials but can do in class'), (4, 'Cant do in class'), (5, 'Never Tried')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moves',
            name='difficulty_remembering',
            field=models.CharField(blank=True, choices=[(1, 'Easy'), (2, 'Good'), (3, 'Again')], max_length=20, null=True),
        ),
    ]
