# Generated by Django 4.0.10 on 2023-05-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0005_alter_moves_difficulty_of_move_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combos',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='combos',
            name='difficulty_of_move',
            field=models.CharField(blank=True, choices=[('1', 'Can always do in socials'), ('2', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('4', 'Cant do in class'), ('5', 'Never Tried')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='combos',
            name='difficulty_remembering',
            field=models.CharField(blank=True, choices=[('1', 'Easy'), ('2', 'Good'), ('3', 'Again')], max_length=20, null=True),
        ),
    ]
