# Generated by Django 4.0.10 on 2023-05-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0006_remove_combos_difficulty_combos_difficulty_of_move_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combohistory',
            name='difficulty_rating',
        ),
        migrations.RemoveField(
            model_name='moveshistory',
            name='difficulty_rating',
        ),
        migrations.AddField(
            model_name='combohistory',
            name='difficulty_remembering',
            field=models.CharField(blank=True, choices=[('1', 'Easy'), ('2', 'Good'), ('3', 'Again')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moveshistory',
            name='difficulty_remembering',
            field=models.CharField(blank=True, choices=[('1', 'Easy'), ('2', 'Good'), ('3', 'Again')], max_length=20, null=True),
        ),
    ]
