# Generated by Django 4.0.10 on 2023-05-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0007_remove_combohistory_difficulty_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combohistory',
            name='difficulty_of_move',
            field=models.CharField(blank=True, choices=[('1', 'Can always do in socials'), ('2', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('4', 'Cant do in class'), ('5', 'Never Tried')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moveshistory',
            name='difficulty_of_move',
            field=models.CharField(blank=True, choices=[('1', 'Can always do in socials'), ('2', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('4', 'Cant do in class'), ('5', 'Never Tried')], max_length=20, null=True),
        ),
    ]
