# Generated by Django 4.0.10 on 2023-05-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0008_combohistory_difficulty_of_move_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combohistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='moveshistory',
            name='user',
        ),
    ]
