# Generated by Django 4.0.10 on 2023-05-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0009_remove_combohistory_user_remove_moveshistory_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovesHistory',
            new_name='MoveHistory',
        ),
        migrations.RenameModel(
            old_name='Moves',
            new_name='Move',
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty_remembering', models.CharField(blank=True, choices=[('1', 'Easy'), ('2', 'Good'), ('3', 'Again')], max_length=20, null=True)),
                ('difficulty_of_move', models.CharField(blank=True, choices=[('1', 'Can always do in socials'), ('2', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('4', 'Cant do in class'), ('5', 'Never Tried')], max_length=20, null=True)),
                ('video_link', models.CharField(blank=True, max_length=255, null=True)),
                ('Move', models.ManyToManyField(to='salsa_app.move')),
            ],
        ),
        migrations.AlterField(
            model_name='combohistory',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salsa_app.combo'),
        ),
        migrations.DeleteModel(
            name='Combos',
        ),
    ]
