# Generated by Django 4.0.10 on 2023-05-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0012_combo_easiness_factor_combo_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='easiness_factor',
        ),
        migrations.RemoveField(
            model_name='combohistory',
            name='easiness_factor',
        ),
        migrations.RemoveField(
            model_name='move',
            name='easiness_factor',
        ),
        migrations.RemoveField(
            model_name='movehistory',
            name='easiness_factor',
        ),
        migrations.AlterField(
            model_name='combo',
            name='difficulty_remembering',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Good'), ('3', 'Again')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='combohistory',
            name='difficulty_of_move',
            field=models.CharField(choices=[('1', 'Can always do in socials'), ('2', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('4', 'Cant do in class'), ('5', 'Never Tried')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='combohistory',
            name='difficulty_remembering',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Good'), ('3', 'Again')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='move',
            name='difficulty_remembering',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Good'), ('3', 'Again')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='movehistory',
            name='difficulty_remembering',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Good'), ('3', 'Again')], default=0, max_length=20),
        ),
    ]
