# Generated by Django 4.0.10 on 2023-05-09 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0013_remove_combo_easiness_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='easiness_factor_remembering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='combohistory',
            name='date_next_review',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='combohistory',
            name='easiness_factor_remembering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='date_next_review',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='move',
            name='easiness_factor_remembering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movehistory',
            name='date_next_review',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='movehistory',
            name='easiness_factor_remembering',
            field=models.IntegerField(default=0),
        ),
    ]
