# Generated by Django 4.0.10 on 2023-05-09 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0014_combo_easiness_factor_remembering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='date_next_review',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
