# Generated by Django 4.0.10 on 2023-05-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0015_combo_date_next_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='difficulty_of_move',
            field=models.CharField(blank=True, choices=[('5', 'Can always do in socials'), ('4', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('2', 'Cant do in class'), ('1', 'Never Tried')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='difficulty_remembering',
            field=models.CharField(choices=[('3', 'Easy'), ('2', 'Good'), ('1', 'Again')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='combohistory',
            name='difficulty_of_move',
            field=models.CharField(choices=[('5', 'Can always do in socials'), ('4', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('2', 'Cant do in class'), ('1', 'Never Tried')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='combohistory',
            name='difficulty_remembering',
            field=models.CharField(choices=[('3', 'Easy'), ('2', 'Good'), ('1', 'Again')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='move',
            name='difficulty_of_move',
            field=models.CharField(blank=True, choices=[('5', 'Can always do in socials'), ('4', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('2', 'Cant do in class'), ('1', 'Never Tried')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='difficulty_remembering',
            field=models.CharField(choices=[('3', 'Easy'), ('2', 'Good'), ('1', 'Again')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='movehistory',
            name='difficulty_of_move',
            field=models.CharField(blank=True, choices=[('5', 'Can always do in socials'), ('4', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('2', 'Cant do in class'), ('1', 'Never Tried')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movehistory',
            name='difficulty_remembering',
            field=models.CharField(choices=[('3', 'Easy'), ('2', 'Good'), ('1', 'Again')], default=0, max_length=20),
        ),
    ]
