# Generated by Django 4.0.10 on 2023-05-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0016_alter_combo_difficulty_of_move_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='base_move',
        ),
        migrations.AlterField(
            model_name='combo',
            name='difficulty_of_move',
            field=models.CharField(blank=True, choices=[('5', 'Can always do in socials'), ('4', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('4', 'Cant do in class'), ('5', 'Never Tried')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='combohistory',
            name='difficulty_of_move',
            field=models.CharField(choices=[('5', 'Can always do in socials'), ('4', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('4', 'Cant do in class'), ('5', 'Never Tried')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='move',
            name='difficulty_of_move',
            field=models.CharField(blank=True, choices=[('5', 'Can always do in socials'), ('4', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('4', 'Cant do in class'), ('5', 'Never Tried')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movehistory',
            name='difficulty_of_move',
            field=models.CharField(blank=True, choices=[('5', 'Can always do in socials'), ('4', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('4', 'Cant do in class'), ('5', 'Never Tried')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('moves', models.ManyToManyField(related_name='positions', to='salsa_app.move')),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salsa_app.position'),
        ),
    ]
