# Generated by Django 4.0.10 on 2023-05-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0018_positionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='position',
        ),
    ]
