# Generated by Django 4.0.10 on 2023-05-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0020_position_date_next_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='entry_hold',
            field=models.CharField(blank=True, choices=[('Left2Left', 'Left2Left'), ('Right2Right', 'Right2Right'), ('Right2Left', 'Right2Left'), ('Left2Right', 'Left2Right'), ('ClosedPosition', 'ClosedPosition'), ('Both Normal Hold', 'Both Normal Hold'), ('BodyWrap-LeftOverRight', 'BodyWrap-LeftOverRight'), ('BodyWrap-RightOverLeft', 'BodyWrap-RightOverLeft'), ('Both - Right Over Left', 'Both - Right Over Left'), ('Free Spin', 'Free Spin')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='exit_hold',
            field=models.CharField(blank=True, choices=[('Left2Left', 'Left2Left'), ('Right2Right', 'Right2Right'), ('Right2Left', 'Right2Left'), ('Left2Right', 'Left2Right'), ('ClosedPosition', 'ClosedPosition'), ('Both Normal Hold', 'Both Normal Hold'), ('BodyWrap-LeftOverRight', 'BodyWrap-LeftOverRight'), ('BodyWrap-RightOverLeft', 'BodyWrap-RightOverLeft'), ('Both - Right Over Left', 'Both - Right Over Left'), ('Free Spin', 'Free Spin')], max_length=40, null=True),
        ),
    ]
