# Generated by Django 4.0.10 on 2023-05-18 08:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salsa_app', '0021_alter_move_entry_hold_alter_move_exit_hold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entry_hold', models.CharField(blank=True, choices=[('Left2Left', 'Left2Left'), ('Right2Right', 'Right2Right'), ('Right2Left', 'Right2Left'), ('Left2Right', 'Left2Right'), ('ClosedPosition', 'ClosedPosition'), ('Both Normal Hold', 'Both Normal Hold'), ('BodyWrap-LeftOverRight', 'BodyWrap-LeftOverRight'), ('BodyWrap-RightOverLeft', 'BodyWrap-RightOverLeft'), ('Both - Right Over Left', 'Both - Right Over Left'), ('Both - Left Over Right', 'Both - Left Over Right'), ('Free Spin', 'Free Spin')], max_length=40, null=True)),
                ('exit_hold', models.CharField(blank=True, choices=[('Left2Left', 'Left2Left'), ('Right2Right', 'Right2Right'), ('Right2Left', 'Right2Left'), ('Left2Right', 'Left2Right'), ('ClosedPosition', 'ClosedPosition'), ('Both Normal Hold', 'Both Normal Hold'), ('BodyWrap-LeftOverRight', 'BodyWrap-LeftOverRight'), ('BodyWrap-RightOverLeft', 'BodyWrap-RightOverLeft'), ('Both - Right Over Left', 'Both - Right Over Left'), ('Both - Left Over Right', 'Both - Left Over Right'), ('Free Spin', 'Free Spin')], max_length=40, null=True)),
                ('difficulty_remembering', models.CharField(choices=[('3', 'Easy'), ('2', 'Good'), ('1', 'Again')], default=0, max_length=20)),
                ('easiness_factor_remembering', models.IntegerField(default=0)),
                ('date_next_review', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('difficulty_of_move', models.CharField(blank=True, choices=[('5', 'Can always do in socials'), ('4', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('4', 'Cant do in class'), ('5', 'Never Tried')], max_length=20, null=True)),
                ('video_link', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('repetition', models.IntegerField(default=0)),
                ('interval', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='move',
            name='entry_hold',
            field=models.CharField(blank=True, choices=[('Left2Left', 'Left2Left'), ('Right2Right', 'Right2Right'), ('Right2Left', 'Right2Left'), ('Left2Right', 'Left2Right'), ('ClosedPosition', 'ClosedPosition'), ('Both Normal Hold', 'Both Normal Hold'), ('BodyWrap-LeftOverRight', 'BodyWrap-LeftOverRight'), ('BodyWrap-RightOverLeft', 'BodyWrap-RightOverLeft'), ('Both - Right Over Left', 'Both - Right Over Left'), ('Both - Left Over Right', 'Both - Left Over Right'), ('Free Spin', 'Free Spin')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='exit_hold',
            field=models.CharField(blank=True, choices=[('Left2Left', 'Left2Left'), ('Right2Right', 'Right2Right'), ('Right2Left', 'Right2Left'), ('Left2Right', 'Left2Right'), ('ClosedPosition', 'ClosedPosition'), ('Both Normal Hold', 'Both Normal Hold'), ('BodyWrap-LeftOverRight', 'BodyWrap-LeftOverRight'), ('BodyWrap-RightOverLeft', 'BodyWrap-RightOverLeft'), ('Both - Right Over Left', 'Both - Right Over Left'), ('Both - Left Over Right', 'Both - Left Over Right'), ('Free Spin', 'Free Spin')], max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='ShineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_practiced', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('date_last_practiced_social', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('date_next_review', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('difficulty_remembering', models.CharField(choices=[('3', 'Easy'), ('2', 'Good'), ('1', 'Again')], default=0, max_length=20)),
                ('easiness_factor_remembering', models.IntegerField(default=0)),
                ('difficulty_of_move', models.CharField(blank=True, choices=[('5', 'Can always do in socials'), ('4', 'Can sometimes do in socials'), ('3', 'Cant do in socials but can do in class'), ('4', 'Cant do in class'), ('5', 'Never Tried')], max_length=20, null=True)),
                ('repetition', models.IntegerField(default=0)),
                ('interval', models.IntegerField(default=0)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salsa_app.shine')),
            ],
        ),
    ]
