# Generated by Django 4.0.10 on 2023-05-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('salsa_app', '0025_alter_combo_user_alter_combohistory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='salsa_app_user_set', related_query_name='salsa_app_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='salsa_app_user_set', related_query_name='salsa_app_user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
